[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache_forge"
solc_version = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
bytecode_hash = "ipfs"

[[profile.default.fs_permissions]]
access = "read"
path = "test/fixtures"

[[profile.default.fs_permissions]]
access = "read"
path = "out"

[fuzz]
runs = 10000
max_test_rejects = 65536

[invariant]
runs = 512
depth = 128
fail_on_revert = false

[fmt]
line_length = 140

[profile.ci]
fuzz = { runs = 20000 }
invariant = { runs = 1024 }